[[table]]
hiragana = "あ"
romaji = "a"

[[table]]
hiragana = "い"
romaji = "i"

[[table]]
hiragana = "う"
romaji = "u"

[[table]]
hiragana = "え"
romaji = "e"

[[table]]
hiragana = "お"
romaji = "o"

[[table]]
hiragana = "ぁ"
romaji = "ka"

[[table]]
hiragana = "き"
romaji = "ki"

[[table]]
hiragana = "く"
romaji = "ku"

[[table]]
hiragana = "け"
romaji = "ke"

[[table]]
hiragana = "こ"
romaji = "ko"

[[table]]
hiragana = "さ"
romaji = "sa"

[[table]]
hiragana = "し"
romaji = "si"  # shi

[[table]]
hiragana = "す"
romaji = "su"

[[table]]
hiragana = "せ"
romaji = "se"

[[table]]
hiragana = "そ"
romaji = "so"

[[table]]
hiragana = "た"
romaji = "ta"

[[table]]
hiragana = "ち"
romaji = "ti"  # chi

[[table]]
hiragana = "つ"
romaji = "tu"  # tsu

[[table]]
hiragana = "て"
romaji = "te"

[[table]]
hiragana = "な"
romaji = "na"

[[table]]
hiragana = "に"
romaji = "ni"

[[table]]
hiragana = "ぬ"
romaji = "nu"

[[table]]
hiragana = "ね"
romaji = "ne"

[[table]]
hiragana = "の"
romaji = "no"

[[table]]
hiragana = "は"
romaji = "ha"

[[table]]
hiragana = "ひ"
romaji = "hi"

[[table]]
hiragana = "ふ"
romaji = "hu"  # fu

[[table]]
hiragana = "へ"
romaji = "he"

[[table]]
hiragana = "ほ"
romaji = "ho"

[[table]]
hiragana = "ま"
romaji = "ma"

[[table]]
hiragana = "み"
romaji = "mi"

[[table]]
hiragana = "む"
romaji = "mu"

[[table]]
hiragana = "め"
romaji = "me"

[[table]]
hiragana = "も"
romaji = "mo"

[[table]]
hiragana = "や"
romaji = "ya"

[[table]]
hiragana = "ゆ"
romaji = "yu"

[[table]]
hiragana = "よ"
romaji = "yo"

[[table]]
hiragana = "ら"
romaji = "ra"

[[table]]
hiragana = "り"
romaji = "ri"

[[table]]
hiragana = "る"
romaji = "ru"

[[table]]
hiragana = "れ"
romaji = "re"

[[table]]
hiragana = "ろ"
romaji = "ro"

[[table]]
hiragana = "わ"
romaji = "wa"

[[table]]
hiragana = "を"
romaji = "wo"

[[table]]
hiragana = "ん"
romaji = "n"
